[package]
name = "trs"
version = "0.1.0"
authors = ["Luro02 <luro02@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rust-crypto = "^0.2"
hex = "0.3.2"
log = "0.4"

[dependencies.byteorder]
version = "1"
features = ["i128"]

[build-dependencies]
cc = "*"
